version: "3.8"
services:
# サービス名はdevcontainer.jsonのファイル内と一致させる
  alma01ver8:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    image: alma01ver8i
    init: true
    container_name: alma01ver8c
    hostname: tako8
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/sakura/unit_labo/redhats:/wrk:cached

