version: "3.3"
services:
  sample-xxx:
    build: 
      context: .
      dockerfile: Dockerfile
    image: sample-i0
    init: true
    container_name: sample-c0
    hostname: sample0
    stdin_open: true
    tty: true
    # user: yamanaka試しにテスト 2021/04/03 →中止

