version: "3.8"
services:
# サービス名はdevcontainer.jsonのファイル内と一致させる
  cpp-kaede3v:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    command: ['zsh']
    image: cpp-kaede-i3v
    init: true
    container_name: cpp-kaede-c3v
    hostname: cppkaede3v
    # https://zenn.dev/iidadaiti/articles/a0b5c540cb10d2
    # あちこちフォルダ移動するとエラーが出てうっとうしい 2022/06/25
    # ホームディレクトリに移動時エラー
    # command: sleep infinity
    stdin_open: true
    tty: true
    volumes:
      - /home/yamanaka/unit_labo/cpplabo:/code:cached
    # user: yamanaka試しにテスト 2021/04/03 →中止

