version: "3.8"
services:
# サービス名はdevcontainer.jsonのファイル内と一致させる
  ruriapp:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    image: ruri02i
    init: true
    container_name: ruri02c
    hostname: ruri02
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/sakura/unit_labo/rust:/wrk:cached

