version: "3.8"
services:
# サービス名はdevcontainer.jsonのファイル内と一致させる
  node-nao1:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    image: node-nao1i-2
    init: true
    container_name: node-nao1c-2
    hostname: nodenao1
    stdin_open: true
    tty: true
    volumes:
      - /home/yamanaka/unit_labo/node1:/wrk:cached
      - /mnt/c:/mnt/c:cached
    # user: yamanaka試しにテスト 2021/04/03 →中止

