version: "3.3"
services:
# サービス名はdevcontainer.jsonのファイル内と一致させる
  sample-3:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    image: sample-i3
    init: true
    container_name: sample-c3
    hostname: hst_sample3
    stdin_open: true
    tty: true
    # user: yamanaka試しにテスト 2021/04/03 →中止

