version: "3.8"
services:
# サービス名はdevcontainer.jsonのファイル内と一致させる
  mariko:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    image: mariko1i
    init: true
    container_name: mariko1c
    hostname: mariko
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/sakura/unit_labo/phpmongo:/wrk:cached

