version: "3.8"
services:
# サービス名はdevcontainer.jsonのファイル内と一致させる
  kaede4:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    image: kaede4i
    init: true
    container_name: kaede4c
    hostname: kaede
    # https://zenn.dev/iidadaiti/articles/a0b5c540cb10d2
    # あちこちフォルダ移動するとエラーが出てうっとうしい 2022/06/25
    # ホームディレクトリに移動時エラー
    # command: sleep infinity
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/sakura/unit_labo/cpplabo:/wrk:cached
    #  - /home/yamanaka/unit_labo/cpplabo:/wrk:cached
    # user: yamanaka試しにテスト 2021/04/03 →中止

