version: "3.8"
services:
# サービス名はdevcontainer.jsonのファイル内と一致させる
  react-rinko1:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    image: react-rinko1-i1
    init: true
    container_name: react-rinko1-c1
    hostname: rinko1
    stdin_open: true
    tty: true
    volumes:
      - /home/yamanaka/unit_labo/react2:/usr/src/app:cached

