version: "3.8"
services:
# サービス名はdevcontainer.jsonのファイル内と一致させる
  cpp-kaede:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    image: cpp-kaede-i
    init: true
    container_name: cpp-kaede-c
    hostname: cppkaede
    stdin_open: true
    tty: true
    volumes:
      - /home/yamanaka/unit_labo/cpplabo:/labo:cache
    # user: yamanaka試しにテスト 2021/04/03 →中止

