version: "3.8"
services:
# サービス名はdevcontainer.jsonのファイル内と一致させる
  ruby-ruriko1:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    command: ['zsh']
    image: ruby-ruriko1i
    init: true
    container_name: ruby-ruriko1c
    hostname: ruriko1
    # https://zenn.dev/iidadaiti/articles/a0b5c540cb10d2
    # あちこちフォルダ移動するとエラーが出てうっとうしい 2022/06/25
    # ホームディレクトリに移動時エラー
    # command: sleep infinity
    stdin_open: true
    tty: true
    volumes:
      - /home/yamanaka/unit_labo/ruby1:/wrk:cached
    # user: yamanaka試しにテスト 2021/04/03 →中止

