version: "3.3"
services:
  cppdev-alpine-sakura1:
    build:
      context: .
      dockerfile: Dockerfile
    image: cppdev-alpine-sakura1-i
    init: true
    container_name: cppdev-alpine-sakura1-c
    volumes: 
      - type: bind
        source: .
        target: /arena
    stdin_open: true
    tty: true
    working_dir: /arena/src/build