version: "3.3"
services:
# サービス名はdevcontainer.jsonのファイル内と一致させる
  ika_sanae:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    image: ika_sanae-i1
    init: true
    container_name: ika_sanae-c1
    hostname: sanae
    stdin_open: true
    tty: true
    # user: yamanaka試しにテスト 2021/04/03 →中止

