version: "3.8"
services:
# サービス名はdevcontainer.jsonのファイル内と一致させる
  java-ayame1:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    image: ayame1i
    init: true
    container_name: ayama1c
    hostname: java
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/sakura/unit_labo/java:/wrk:cached

